public with sharing class TestData {

  public static final String LOGIN = 'Xixiao007';
  public static final String HTML_URL = 'https://github.com/Xixiao007';
  public static final Integer PUBLIC_REPOS = 58;
  public static final Integer PUBLIC_GISTS = 9;
  public static final String XIXIAO007_SUCCESS_RESPONSE = '{"login":"' +
                                                          LOGIN  + '","id":13655323,"node_id":"MDQ6VXNlcjEzNjU1MzIz","avatar_url":"https://avatars0.githubusercontent.com/u/13655323?v=4","gravatar_id":"","url":"https://api.github.com/users/Xixiao007","html_url":"' +
                                                          HTML_URL + '","followers_url ":"https://api.github.com/users/Xixiao007/followers","following_url":"https://api.github.com/users/Xixiao007/following{/other_user}","gists_url":"https://api.github.com/users/Xixiao007/gists{/gist_id}","starred_url":"https://api.github.com/users/Xixiao007/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Xixiao007/subscriptions","organizations_url":"https://api.github.com/users/Xixiao007/orgs","repos_url":"https://api.github.com/users/Xixiao007/repos","events_url":"https://api.github.com/users/Xixiao007/events{/privacy}","received_events_url":"https://api.github.com/users/Xixiao007/received_events","type":"User","site_admin":false,"name":"XiXiao","company":null,"blog":"http://xixiao.info","location":"Finland","email":null,"hireable":null,"bio":null,"public_repos":' +
                                                          PUBLIC_REPOS + ',"public_gists":' +
                                                          PUBLIC_GISTS + ',"followers":2,"following":0,"created_at":"2015-08-05T06:39:13Z","updated_at":"2018-12-23T21:18:48Z"}';
}
